services:
  web:
    image: nginx:latest
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./server:/etc/nginx/conf.d



    ports:
      - 80:80
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - php
      - db


  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: legotech
      POSTGRES_USER: legotech
      POSTGRES_PASSWORD: "05092004"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/db-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - app-network
  php_test:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env.testing
    networks:
      - app-network
    depends_on:
      - db
  php_dusk:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env.dusk.local
    networks:
      - app-network
    depends_on:
      - db
      - selenium


networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
