#!/bin/bash
set -o errexit
set -o pipefail

source .env

function ps {
    docker compose ps
}

function up {
    docker compose up -d "$@"

    docker compose exec php sh -c "
        mkdir -p storage/framework/{cache,views,sessions,testing} bootstrap/cache &&
        chown -R www-data:www-data storage bootstrap/cache &&
        chmod -R 775 storage bootstrap/cache
    "

    docker compose exec php php artisan key:generate
}

function down {
    docker compose down "$@"
}

function composer {
    docker compose run --rm php composer "$@"
}

function tests {
    echo "Clearing caches..."
    docker compose exec -T php_test php artisan config:clear
    docker compose exec -T php_test php artisan cache:clear
    docker compose exec -T php_test php artisan route:clear

    echo "Running migrations..."
    docker compose exec -T php_test php artisan migrate:fresh --force

    echo "Running PHPUnit..."
    docker compose exec -T php_test ./vendor/bin/phpunit --colors=always
}

function dusk {
    echo "=== Switching NGINX to DUSK CONFIG ==="
    docker compose exec web sh -c "echo 'include /etc/nginx/conf.d/nginx.dusk.conf;' > /etc/nginx/conf.d/default.conf"
    docker compose exec web nginx -s reload

    echo 'Resetting DB...'
    docker compose exec -T php_test php artisan migrate:fresh --force --env=dusk

    echo "Running Dusk..."
    docker compose exec -T php_test php artisan dusk --env=dusk

    echo "=== Restoring normal NGINX config ==="
    docker compose exec web sh -c "echo 'include /etc/nginx/conf.d/nginx.dev.conf;' > /etc/nginx/conf.d/default.conf"
    docker compose exec web nginx -s reload
}



function phpcs {
    TEST_PATH="${@:-.}"
    docker compose run --rm php ./vendor/bin/phpcs -d memory_limit=1G ${TEST_PATH}
}

function phpcbf {
    TEST_PATH="${@:-.}"
     docker compose run --rm php ./vendor/bin/phpcbf -d memory_limit=1G ${TEST_PATH}
}

function phpstan {
    TEST_PATH="${@:-}"
    docker compose run --rm php ./vendor/bin/phpstan analyse --memory-limit 1G ${TEST_PATH}
}

function git:clean:branchs {
    git branch | grep -v '\*\|master\|main\|develop\|production' | xargs -n 1 git branch -D
}

function db:console {
    docker compose exec db psql -U ${DB_USERNAME} -d ${DB_DATABASE}
}

function db:reset {
    docker compose exec php php artisan migrate:fresh --seed
}

function db:populate {
    docker compose exec php php artisan db:seed
}


TIMEFORMAT=$'\nTask completed in %3lR'
time "$@"
