#!/bin/bash
set -o errexit
set -o pipefail

source .env

#
# Função para restaurar NGINX (é executada SEMPRE ao final do script)
#
function restore_nginx {
    echo "=== Restoring DEV CONFIG ==="
    docker compose cp server/nginx.dev.conf web:/etc/nginx/conf.d/default.conf || true
    docker compose restart web || true
}

function ps {
    docker compose ps
}

function up {
    docker compose up -d "$@"

    docker compose exec php sh -c "
        mkdir -p storage/framework/{cache,views,sessions,testing} bootstrap/cache &&
        chown -R www-data:www-data storage bootstrap/cache &&
        chmod -R 775 storage bootstrap/cache
    "

    docker compose exec php php artisan key:generate
}

function down {
    docker compose down "$@"
}

function composer {
    docker run --rm -i \
        -e COMPOSER_CACHE_DIR="/app/.cache/composer" \
        -u 0:0 \
        -v "$(pwd):/app" \
        -w /app \
        composer:2.7.2 composer "${@}"
}

function tests {
    echo "Clearing caches..."
    docker compose exec -T php_test php artisan config:clear
    docker compose exec -T php_test php artisan cache:clear
    docker compose exec -T php_test php artisan route:clear

    echo "Running migrations..."
    docker compose exec -T php_test php artisan migrate:fresh --force

    echo "Running PHPUnit..."
    docker compose exec -T php_test ./vendor/bin/phpunit --colors=always
}

function dusk {
    echo "=== Switching to DUSK CONFIG ==="

    # GARANTE que nginx será restaurado MESMO se dusk falhar
    trap restore_nginx EXIT

    docker compose cp server/nginx.dusk.conf web:/etc/nginx/conf.d/default.conf
    docker compose restart web

    echo "Resetting DB..."
    docker compose exec -T php_test php artisan migrate:fresh --force --env=dusk

    echo "Running Dusk..."
    # NÃO aborta script se dusk falhar
    docker compose exec -T php_test php artisan dusk --env=dusk || true
}

function phpcs {
    TEST_PATH="${@:-.}"
    docker compose run --rm php ./vendor/bin/phpcs -d memory_limit=1G ${TEST_PATH}
}

function phpcbf {
    TEST_PATH="${@:-.}"
     docker compose run --rm php ./vendor/bin/phpcbf -d memory_limit=1G ${TEST_PATH}
}

function phpstan {
    TEST_PATH="${@:-}"
    docker compose run --rm php ./vendor/bin/phpstan analyse --memory-limit 1G ${TEST_PATH}
}

function git:clean:branchs {
    git branch | grep -v '\*\|master\|main\|develop\|production' | xargs -n 1 git branch -D
}

function db:console {
    docker compose exec db psql -U ${DB_USERNAME} -d ${DB_DATABASE}
}

function db:reset {
    docker compose exec php php artisan migrate:fresh --seed
}

function db:populate {
    docker compose exec php php artisan db:seed
}

TIMEFORMAT=$'\nTask completed in %3lR'
time "$@"
